application:
  name: to-do-api
  server:
    port: 8080

  security:
    allowed-origins: http://localhost:8080
    jwt:
      signing-key: kKJ1broVO1hn2yoRK19jCOfSO0iEyxcH38x3s5VJyEs=
      TOKEN_EXPIRATION_TIME: 3600000

spring:
  datasource:
    url:
    username:
    password:

