spring:
  application:
    name: ${application.name}

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update

server:
  servlet:
    context-path: /api/v1
  port: ${application.server.port}

application:
  security:
    allowed-origins: ${security.cors.allowed.origins}
    jwt:
      signing-key: ${application.security.jwt.signing-key}
      TOKEN_EXPIRATION_TIME: ${security.authentication.jwt.TOKEN_EXPIRATION_TIME}
