spring:
  profiles:
    active: dev

  application:
    name: ${application.name}

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  jpa:
    database: ${spring.jpa.database}
    database-platform: ${spring.jpa.database-platform}
    properties:
      hibernate:
        format_sql: ${spring.jpa.properties.hibernate.format_sql}
        hbm2ddl:
          auto: ${spring.jpa.properties.hibernate.hbm2ddl.auto}
    open-in-view: ${spring.jpa.open-in-view}

server:
  servlet:
    context-path: /api/v1
  port: ${application.server.port}

application:
  security:
    allowed-origins: ${application.security.allowed-origins}
    jwt:
      signing-key: ${application.security.jwt.signing-key}
      access-token-expiration: ${application.security.jwt.access-token-expiration}
    opaque:
      refresh-token-expiration: ${application.security.opaque.refresh-token-expiration}
