
# get all todos
GET http://localhost:8080/api/v1/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0b2RvLWFwaS1zcHJpbmciLCJpYXQiOjE3MzczMjYxOTcsInN1YiI6ImphbmVfZG9lQG1haWwuY29tIiwiYXV0aG9yaXRpZXMiOltdLCJleHAiOjE3MzczMjcwOTd9.lhPk85UTfmGZUJKndGR3QWkYgSdgbGVeVi8YAli7n-8


# get todo by id
###
GET http://localhost:8080/api/v1/to-do/5
Authorization: Bearer

###
POST http://localhost:8080/api/v1/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0b2RvLWFwaS1zcHJpbmciLCJpYXQiOjE3MzczMjYxOTcsInN1YiI6ImphbmVfZG9lQG1haWwuY29tIiwiYXV0aG9yaXRpZXMiOltdLCJleHAiOjE3MzczMjcwOTd9.lhPk85UTfmGZUJKndGR3QWkYgSdgbGVeVi8YAli7n-8

{
  "title": "Team Meeting Preparation",
  "description": "Prepare the agenda and slides for the upcoming team meeting.",
  "endDate": "2025-02-01T14:30:00",
  "isCompleted": false
}


