name: todo api pipeline

on:
  push:
    branches:
      - master
    paths:
      - src
      - docker
      - .github/workflows/api-pipeline.yaml
      - pom.xml

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-jdk@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Compile project
        run: mvn clean package

  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-jdk@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Extract project version
        id: extract_version
        run: |
          echo "VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Login to docker registery
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image to registery
        run: docker build  -t ${{secrets.DOCKERHUB_USERNAME}}/todo-api:${{secrets.GITHUB_TOKEN}} -f docker/Dockerfile . && | 
             docker push




